package bookingCancel

type Index int

const (
	SHMT_CNTR_PACKG_UUID Index = iota
	TRCKG_GRP_REF_CDE
	TRCKG_GRP_UUID
	F_POL_DEP_TIME_ID
	L_POD_ARR_TIME_ID
	F_BASE_POL_DEP_TIME_ID
	L_BASE_POD_ARR_TIME_ID
	CGO_TRADE_LANE_CDE
	CGO_TRADE_CDE
	F_POL_UUID
	L_POD_UUID
	F_POL_TERMINAL_UUID
	L_POD_TERMINAL_UUID
	F_BASE_POL_UUID
	L_BASE_POD_UUID
	ORIG_CITY_UUID
	ORIG_OFCE_CDE
	ORIG_STATE_NME
	ORIG_COUNTRY_NME
	DEST_CITY_UUID
	DEST_OFCE_CDE
	DEST_STATE_NME
	DEST_COUNTRY_NME
	F_BASE_POL_SVVD
	L_BASE_POD_SVVD
	F_POL_SVVD
	L_POD_SVVD
	CNTR_TYPE
	CNTR_NUM
	BL_REF_CDE
	BL_BASIC_UUID
	CONTROL_UUID
	SHIPPER_UUID
	CONSIGN_UUID
	NOTIFY_UUID
	FORWARD_UUID
	CTRCT_CTRL_UUID
	CTRCT_CTRL_PTY_CDE
	BPM_SALES_OFCE_CDE
	SC_NUM
	AGMT_NUM
	SC_CSO_IND
	SC_CSO_CTRL_PARTY_STAT
	DIR_IND
	ITS_TRADE_CDE
	ITS_TRADE_LANE_CDE
	CGO_NATURE_CDE
	BRIEF_DESC
	SUBST_CNTR_TYPE
	SOC_IND
	IRIS2_SALES_OFCE_CDE
	BKG_OFCE_CDE
	LAST_APP_DT
	LAST_APPROVER
	AGMT_CREATOR
	AGMT_KEY
	F_POL_SALES_OFCE
	L_POD_SALES_OFCE
	F_BASE_POL_SALES_OFCE
	L_BASE_POD_SALES_OFCE
	GROSS_WT_KG
	BKG_PARTY_UUID
	BKG_PARTY_CDE
	BKG_PARTY_NME
	PAYER_CDE
	PRIMARY_SVVD_ID
	PRIMARY_SVVD_POL_UUID
	PRIMARY_SVVD_POD_UUID
	WORKDATE
	REC_LOAD_DTE
	SC_CSO
	INTRA_RIVER_IND
	SALES_CDE
	SALCNTR_SIZE_GRP
	SALCNTR_TYPE_GRP
	DEV_DEGREE
	TRUE_CNTR_TYPE
	PRIMARY_SVVD_CLOSE_DAT
	CGO_TRADE_LANE_DIR
	DEV_DEGREE_DESC
	CUST_ID
	FOB_IND
	IRIS2_ACCOUNT_SCALE
	OB_DR_START_LOC_DT
	OB_DR_CMPL_LOC_DT
	F_POL_DEP_TIME
	L_POD_ARR_TIME
	IB_DR_START_LOC_DT
	IB_DR_CMPL_LOC_DT
	REGION_GRP_MAIN_NME
	GBL_GRP_MAIN_NME
	MTY_PICKUP_FCIL_CDE
	FULL_RTN_FCIL_CDE
	CGO_PICKUP_FCIL_CDE
	MTY_RTN_FCIL_CDE
	SHIPPER_AREA_CDE
	SHIPPER_SALES_OFCE_CDE
	REPORTING_WEEK
	CNTR_TYPE_2014
	CNTR_TYPE_GROUP_2014
	INLAND_CGO_IND
	OB_TERM
	IB_TERM
	TEU
	COMMODITY_GROUP
	BKG_CRE_LOC_DT
	COMMIT_STATUS
	CANCELLED_DATE
)

var TargetMap = map[string]bool{"Cancelled": true}

const (
	inputFile = "C:/Users/YongGang/Documents/数据包/TAO数据20170509.txt"
	//inputFile  = "C:/Users/YongGang/Documents/数据包/TPW数据20170509.txt"
	outputFile = "C:/Users/YongGang/Documents/数据包/sample_out.txt"
	sep        = "\t"
)
